# Generated by Django 6.0.3 on 2026-03-25 02:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuttonchoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_file_upload_path, verbose_name='Загруженный файл'),
        ),
    ]
